### ISSUE TITLE
Are you planning to release to Maven Central Repository

### ISSUE THREAD

**Issue by ao-apps** [prakma/postfix-jilter#1]
We use the jilter-1.2.jar as a dependency of a project that we're moving into Maven Central Repository.  As part of this, all dependencies of our project should also be in the central repository.

Are you planning to publish this to Maven Central?  If not, should we fork it from your work and publish under our groupId?

**Comment by prakma** [comment]
Thanks for checking. I will publish it to Maven Central in a few days.

**Comment by ao-apps** [comment]
Thank you.

**Comment by prakma** [comment]
Sorry it took a while for me to get to it. Working on it now, and hope to
publish it by end of this week. Thought I will just update in case you were
wondering.

**Comment by ao-apps** [comment]
We look forward to it.  Thank you!

**Comment by ao-apps** [comment]
Thank you for taking care of this.  We found it:
https://search.maven.org/artifact/com.github.prakma/postfix-jilter
